# Generated by Django 4.2.7 on 2025-12-14 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_usertoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Giới thiệu'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Giới tính'),
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='user_posts/', verbose_name='Hình ảnh')),
                ('caption', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Mô tả')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.user', verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Bài đăng',
                'verbose_name_plural': 'Bài đăng',
                'db_table': 'users_user_post',
                'ordering': ['-created_at'],
            },
        ),
    ]
