# Generated by Django 4.2.7 on 2025-12-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_user_bio_user_date_of_birth_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Bình luận'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Đánh giá (1-5 sao)'),
        ),
    ]
