# Generated by Django 4.2.7 on 2025-12-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=10, verbose_name='Số hiệu chuyến bay')),
                ('departure', models.CharField(max_length=255, verbose_name='Điểm khởi hành')),
                ('destination', models.CharField(max_length=255, verbose_name='Điểm đến')),
                ('departure_time', models.DateTimeField(verbose_name='Thời gian khởi hành')),
                ('arrival_time', models.DateTimeField(verbose_name='Thời gian đến')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('airline', models.CharField(max_length=255, verbose_name='Hãng hàng không')),
                ('seats_available', models.PositiveIntegerField(default=0, verbose_name='Số ghế còn trống')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Chuyến bay',
                'verbose_name_plural': 'Chuyến bay',
                'db_table': 'flight_flight',
                'ordering': ['-created_at'],
            },
        ),
    ]
