# Sử dụng Python base image
FROM python:3.10-slim

# Tắt bytecode + bật log real-time
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Tạo thư mục làm việc
WORKDIR /app

# Cài các gói cần thiết để build
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Cài đặt dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy toàn bộ mã nguồn
COPY . .

# Mở cổng Django
EXPOSE 8000

# Lệnh chạy server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
