# Generated by Django 4.2.7 on 2025-12-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên khách sạn')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('location', models.CharField(max_length=255, verbose_name='Địa điểm')),
                ('amenities', models.TextField(verbose_name='Tiện nghi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Hình ảnh')),
                ('rooms_available', models.PositiveIntegerField(default=0, verbose_name='Số phòng còn trống')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Khách sạn',
                'verbose_name_plural': 'Khách sạn',
                'db_table': 'hotels_hotel',
                'ordering': ['-created_at'],
            },
        ),
    ]
