# Generated by Django 4.2.7 on 2025-12-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên tour')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('duration', models.IntegerField(verbose_name='Số ngày')),
                ('location', models.CharField(max_length=255, verbose_name='Địa điểm')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tour',
                'db_table': 'tours_tour',
                'ordering': ['-created_at'],
            },
        ),
    ]
