# Generated by Django 4.2.7 on 2025-12-11 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('users', '0002_alter_user_options_alter_usertoken_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tours', '__first__'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('best_season', models.CharField(blank=True, max_length=120)),
                ('tags', models.CharField(blank=True, help_text='CSV tags, vd: beach,adventure,family', max_length=255)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_destination',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5, unique=True)),
                ('visa_required', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'catalog_visarequirement',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.user')),
            ],
            options={
                'db_table': 'catalog_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('label', models.CharField(blank=True, choices=[('family', 'Gia đình'), ('couple', 'Cặp đôi'), ('adventure', 'Phiêu lưu'), ('luxury', 'Cao cấp'), ('budget', 'Tiết kiệm')], max_length=50)),
                ('rating_cached', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='catalog.destination')),
                ('flights', models.ManyToManyField(blank=True, related_name='packages', to='flight.flight')),
                ('hotels', models.ManyToManyField(blank=True, related_name='packages', to='hotels.hotel')),
                ('tours', models.ManyToManyField(blank=True, related_name='packages', to='tours.tour')),
            ],
            options={
                'db_table': 'catalog_package',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.user')),
            ],
            options={
                'db_table': 'catalog_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AirlineFareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('vietjet', 'VietJet Air'), ('bamboo', 'Bamboo Airways'), ('vna', 'Vietnam Airlines'), ('viettravel', 'Vietravel Airlines')], max_length=20)),
                ('route_type', models.CharField(choices=[('domestic', 'Nội địa'), ('international', 'Quốc tế')], max_length=20)),
                ('trip_type', models.CharField(choices=[('oneway', 'Một chiều'), ('roundtrip', 'Khứ hồi')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('multiplier_advance', models.DecimalField(decimal_places=4, default=0.01, help_text='Hệ số tăng theo số ngày đặt trước', max_digits=6)),
                ('tax_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalog_airlinefarerule',
                'unique_together': {('carrier', 'route_type', 'trip_type')},
            },
        ),
    ]
