# Generated by Django 4.2.7 on 2025-12-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('tours', '0001_initial'),
        ('catalog', '0001_initial'),
        ('users', '0004_userpost_comment_userpost_rating'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_type', models.CharField(choices=[('tour', 'Tour'), ('hotel', 'Hotel'), ('flight', 'Flight')], max_length=10, verbose_name='Loại đặt chỗ')),
                ('booking_date', models.DateField(verbose_name='Ngày đặt')),
                ('number_of_people', models.IntegerField(verbose_name='Số người')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng giá')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight', verbose_name='Chuyến bay')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel', verbose_name='Khách sạn')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.package', verbose_name='Gói gợi ý')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tour', verbose_name='Tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đặt chỗ',
                'verbose_name_plural': 'Đặt chỗ',
                'db_table': 'bookings_booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=255, verbose_name='Tên hành khách')),
                ('flight_details', models.TextField(blank=True, verbose_name='Chi tiết chuyến bay/xe bus')),
                ('hotel_room_details', models.TextField(blank=True, verbose_name='Chi tiết phòng khách sạn')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng chi phí')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Phương thức thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='bookings.booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Vé',
                'verbose_name_plural': 'Vé',
                'db_table': 'bookings_ticket',
                'ordering': ['-created_at'],
            },
        ),
    ]
